#!/bin/sh

echo """Welcome to git-shell on $(uname -n)!

Available Commands:
ls: list all repositories.
init <name>: Initialize new Git repository with <name>
rm <name>: Delete Git repository with <name>
"""
